### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by hardlydavis** [peterpakos/bamboo_ipa_sync#1]
Hi there,
I've been enjoying testing this out, really appreciate the work here.
I just wanted to clarify under what terms or license this is being made available?

Best,

David

**Comment by peterpakos** [comment]
Hi @hardlydavis, I'm glad you like the project.

It comes with GPLv3 license.

I'll make sure the licensing info is included in the next release.

Feel free to highlight any improvement ideas or issues found.

Cheers.
